# ========================================================
#              BanHammer Configuration File
# ========================================================

# Custom Model Data for Resource Pack texture (mace_banhammertexture.png)
custom-model-data: 1001

# Automatic Integrated Resource Pack Server Settings
resource-pack:
  enabled: true
  auto-send-on-join: true
  port: 8085

# Hit Effects Settings
effects:
  lightning: true
  explosion: true
  sound: true
  particles: true
  
  # Potion Effects applied to victim on hit
  potion-effects:
    BLINDNESS:
      duration-seconds: 5
      amplifier: 1
    SLOWNESS:
      duration-seconds: 10
      amplifier: 2

# Messages Configuration
messages:
  prefix: "<gradient:#FF0033:#FFD700><bold>BanHammer</bold></gradient> <gray>»</gray> "
  broadcast: "<prefix><red><player></red> <gray>a été frappé et ban par le BanHammer !</gray>"
  ban-reason: "<red>Vous avez été ban par le BanHammer.</red>"
  no-permission: "<prefix><red>Vous n'avez pas la permission d'utiliser cet objet légendaire.</red>"
